version: "2.4"
services:
  tooling:
    image: ${COMPOSE_PROJECT_NAME}/tooling
    build:
      context: ./docker/build/jss-tools
    scale: 0
  id:
    environment:
      SITECORE_LICENSE_LOCATION: C:\license\license.xml
    volumes:
      - ${HOST_LICENSE_FOLDER}:C:\license
  mssql:
    image: ${COMPOSE_PROJECT_NAME}/mssql
    build:
      context: ./docker/build/mssql
      args: 
        BASE_IMAGE: ${SITECORE_DOCKER_REGISTRY}sitecore-xp0-mssql:${SITECORE_VERSION}
        SPE_IMAGE: ${SITECORE_MODULE_REGISTRY}spe-assets:${SPE_VERSION}
        SXA_IMAGE: ${SITECORE_MODULE_REGISTRY}sxa-xm1-assets:${SXA_VERSION}
        JSS_IMAGE: ${SITECORE_MODULE_REGISTRY}jss-xm1-assets:${JSS_VERSION}
    mem_limit: 2GB
    volumes:
      - ${LOCAL_DATA_PATH}\mssql:c:\data
  solr:
    image: ${COMPOSE_PROJECT_NAME}/solr
    build:
      context: ./docker/build/solr
      args:
        BASE_IMAGE: ${SITECORE_DOCKER_REGISTRY}sitecore-xp0-solr:${SITECORE_VERSION}
        SXA_IMAGE: ${SITECORE_MODULE_REGISTRY}sxa-xm1-assets:${SXA_VERSION}
    mem_limit: 1GB
    volumes:
      - ${LOCAL_DATA_PATH}\solr:c:\data
  cm:
    image: ${COMPOSE_PROJECT_NAME}/cm
    build:
      context: ./docker/build/cm
      args:
        BASE_IMAGE: ${SITECORE_DOCKER_REGISTRY}sitecore-xp0-cm:${SITECORE_VERSION}
        SPE_IMAGE: ${SITECORE_MODULE_REGISTRY}spe-assets:${SPE_VERSION}
        SXA_IMAGE: ${SITECORE_MODULE_REGISTRY}sxa-xm1-assets:${SXA_VERSION}
        JSS_IMAGE: ${SITECORE_MODULE_REGISTRY}jss-xm1-assets:${JSS_VERSION}
        TOOLING_IMAGE: ${SITECORE_TOOLS_REGISTRY}sitecore-docker-tools-assets:${TOOLS_VERSION}
        JSS_TOOLING_IMAGE: ${COMPOSE_PROJECT_NAME}/tooling
    environment:
        SITECORE_LICENSE_LOCATION: C:\license\license.xml
    volumes:
      - ${HOST_LICENSE_FOLDER}:C:\license
      - ${LOCAL_DEPLOY_PATH}\website:C:\deploy
      - ${LOCAL_DATA_PATH}\cm:C:\inetpub\wwwroot\App_Data\logs
    entrypoint: powershell -Command "& C:\tools\entrypoints\iis\Development.ps1"
    mem_limit: 4GB
    depends_on:
      - tooling
  xconnect: 
    volumes:
      - ${HOST_LICENSE_FOLDER}:C:\license
    environment:
      SITECORE_LICENSE_LOCATION: C:\license
  xdbsearchworker:
    volumes:
      - ${HOST_LICENSE_FOLDER}:C:\license
    environment:
      SITECORE_LICENSE_LOCATION: C:\license
  xdbautomationworker:
    volumes:
      - ${HOST_LICENSE_FOLDER}:C:\license
    environment:
      SITECORE_LICENSE_LOCATION: C:\license
  cortexprocessingworker:
    volumes:
      - ${HOST_LICENSE_FOLDER}:C:\license
    environment:
      SITECORE_LICENSE_LOCATION: C:\license