version: "2.4"
services:
  tooling:
    build:
      context: ./docker/build/jss-tools
    scale: 0
  id:
    environment:
      SITECORE_LICENSE_LOCATION: C:\license\license.xml
    volumes:
      - ${HOST_LICENSE_FOLDER}:C:\license
  mssql:
    image: community/sitecore-xp0-custom-sxa-jss-mssql:${SITECORE_VERSION}
    mem_limit: 2GB
    volumes:
      - ${LOCAL_DATA_PATH}\mssql:c:\data
  solr:
    image: community/sitecore-xp0-custom-sxa-solr:${SITECORE_VERSION}
    mem_limit: 1GB
    volumes:
      - ${LOCAL_DATA_PATH}\solr:c:\data
  cm:
    image: community/sitecore-xp0-custom-sxa-jss-cm:${SITECORE_VERSION}
    build:
      context: ./docker/build/cm
      args:
        BASE_IMAGE: community/sitecore-xp0-custom-sxa-jss-cm:${SITECORE_VERSION}
        TOOLING_IMAGE: ${SITECORE_TOOLS_REGISTRY}sitecore-docker-tools-assets:${TOOLS_VERSION}
        JSS_TOOLING_IMAGE: sc10-jss_tooling
    environment:
        SITECORE_LICENSE_LOCATION: C:\license\license.xml
    volumes:
      - ${HOST_LICENSE_FOLDER}:C:\license
      - ${LOCAL_DEPLOY_PATH}\website:C:\deploy
      - ${LOCAL_DATA_PATH}\cm:C:\inetpub\wwwroot\App_Data\logs
    entrypoint: powershell -Command "& C:\tools\entrypoints\iis\Development.ps1"
    mem_limit: 4GB
  xconnect: 
    volumes:
      - ${HOST_LICENSE_FOLDER}:C:\license
    environment:
      SITECORE_LICENSE_LOCATION: C:\license
  xdbsearchworker:
    volumes:
      - ${HOST_LICENSE_FOLDER}:C:\license
    environment:
      SITECORE_LICENSE_LOCATION: C:\license
  xdbautomationworker:
    volumes:
      - ${HOST_LICENSE_FOLDER}:C:\license
    environment:
      SITECORE_LICENSE_LOCATION: C:\license
  cortexprocessingworker:
    volumes:
      - ${HOST_LICENSE_FOLDER}:C:\license
    environment:
      SITECORE_LICENSE_LOCATION: C:\license